# Generated by Django 5.1.3 on 2025-06-15 01:49

import bills.models
import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biller_name', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('scheduled', 'Scheduled'), ('unable_to_pay', 'Unable to Pay'), ('paid', 'Paid')], max_length=50)),
                ('status_context', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=bills.models.bill_thumbnail_upload_folder)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueDate', models.DateField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('scheduled', 'Scheduled'), ('unable_to_pay', 'Unable to Pay'), ('paid', 'Paid')], max_length=50)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='installments', to='bills.bill')),
            ],
        ),
    ]
