# Generated by Django 5.1.3 on 2025-06-15 07:22

import bills.models.bill
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='biller_name',
            new_name='biller',
        ),
        migrations.RenameField(
            model_name='installment',
            old_name='dueDate',
            new_name='due',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='installment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], max_length=50),
        ),
        migrations.CreateModel(
            name='BillImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=bills.models.bill.bill_thumbnail_upload_folder)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bills.bill')),
            ],
        ),
    ]
